name: Production Deploy

on:
  workflow_dispatch:
  workflow_call:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn publish-docs
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_ANT_PROCESS_ID: ${{ secrets.DEPLOY_ANT_PROCESS_ID }}
